[lint]
select = ["E", "F", "W", "C90", "I"]
ignore = []

# Allow B008 to be used for FastAPI dependencies
# See https://github.com/astral-sh/ruff/issues/2942
# flake8-bugbear
# B008 = "Do not perform function calls in argument defaults. The call is performed only once, at function definition time."
# extend-ignore = ["B008"]

# Allow unused variables when underscore-prefixed.
# dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# fixable = ["ALL"]
# unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*/migrations/*",
]
# Same as Black.
line-length = 88
target-version = "py310"

[format]
quote-style = "double"
indent-style = "space"
skip-string-normalization = false
line-ending = "auto" 