[project]
name = "deekseek-to-stt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastrtc[stt,tts,vad]>=0.0.22",
    "langchain[ollama]>=0.3.24",
]
